name: metaphlan-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adapterremoval=2.3.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports_abc=0.5
  - biom-format=2.1.7
  - biopython=1.68
  - bowtie2=2.3.5
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0
  - enum34=1.1.6
  - freetype=2.10.0
  - functools32=3.2.3.2
  - future=0.18.2
  - futures=3.3.0
  - h5py=2.10.0
  - hdf5=1.10.5
  - idna=2.8
  - ipaddress=1.0.23
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libcxx=9.0.0
  - libdeflate=1.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - libtiff=4.1.0
  - linecache2=1.0.0
  - llvm-openmp=9.0.0
  - lz4-c=1.8.3
  - matplotlib=2.2.4
  - matplotlib-base=2.2.4
  - metaphlan2=2.7.5
  - mmtf-python=1.0.2
  - msgpack-python=0.6.2
  - ncurses=6.1
  - numpy=1.16.5
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.24.2
  - perl=5.26.2
  - pillow=6.2.1
  - pip=19.3.1
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.4.5
  - pyqi=0.3.2
  - pysam=0.15.3
  - pysocks=1.7.1
  - python=2.7.15
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=8.0
  - reportlab=3.5.32
  - requests=2.22.0
  - scipy=1.2.1
  - setuptools=41.6.0
  - singledispatch=3.4.0.3
  - six=1.13.0
  - sqlite=3.30.1
  - subprocess32=3.5.4
  - tbb=2019.9
  - tk=8.6.9
  - tornado=5.1.1
  - traceback2=1.4.0
  - unittest2=1.1.0
  - urllib3=1.25.7
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.3
