name: metaphlan-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pip
  - pandas
  - adapterremoval
  - metaphlan=3.0.1
  - samtools
  - mapdamage2
  - damageprofiler
  - multiqc
  - pip:
    - git+https://git@github.com/maxibor/pydamage.git
